services:
  database:
    build:
      context: ./docker/conf/postgres
      dockerfile: Dockerfile
    image: open-metin-postgres-ssl:latest
    restart: unless-stopped
    ports:
      - "10000:5432"
    volumes:
      - ./database-init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/data/database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata

  redis:
    image: redis:8.2.2-alpine
    restart: unless-stopped
    ports:
      - "10001:6379"
    volumes:
      - ./docker/conf/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./docker/conf/redis/certs:/certs:ro
    command: redis-server /usr/local/etc/redis/redis.conf

  rabbitmq:
    image: rabbitmq:4.0.5-management-alpine
    restart: unless-stopped
    ports:
      - "10002:15671"
      - "10003:5671"
    volumes:
      - ./docker/conf/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./docker/conf/rabbitmq/certs:/etc/rabbitmq/certs:ro
    environment:
      - RABBITMQ_CONFIG_FILE=/etc/rabbitmq/rabbitmq
      - RABBITMQ_PROMETHEUS_RETURN_PER_OBJECT_METRICS=true
      - RABBITMQ_PROMETHEUS_EXPORTER=true

  prometheus:
    image: prom/prometheus:v3.8.1
    restart: unless-stopped
    ports:
      - "10004:9090"
    volumes:
      - ./docker/conf/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-remote-write-receiver'
    extra_hosts:
      - "host.docker.internal:host-gateway"

  loki:
    image: grafana/loki:3.5.9
    restart: unless-stopped
    ports:
      - "10005:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./docker/conf/loki/loki.yaml:/etc/loki/local-config.yaml

  tempo:
    image: grafana/tempo:2.9.0
    restart: unless-stopped
    ports:
      - "10006:3200"   # tempo
      - "10007:4317"   # otlp grpc
      - "10008:4318"   # otlp http
    volumes:
      - ./docker/conf/tempo/tempo.yaml:/etc/tempo/tempo.yaml
    command:
      - "-config.file=/etc/tempo/tempo.yaml"

  grafana:
    image: grafana/grafana:12.3.1
    restart: unless-stopped
    ports:
      - "10009:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./docker/conf/grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
    depends_on:
      - prometheus
      - loki
      - tempo