name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        module: [ authentication, game ]

    steps:
      - name: Checkout code â™»ï¸
        uses: actions/checkout@v4

      - name: Set up JDK 25 ğŸ”§
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for gradlew ğŸ›‚
        run: chmod +x gradlew

      - name: Build ${{ matrix.module }} ğŸ”¨
        run: ./gradlew :${{ matrix.module }}:build -x test

      - name: Test ${{ matrix.module }} ğŸ§ª
        run: ./gradlew :${{ matrix.module }}:test

      - name: Upload ${{ matrix.module }} test results âœ…
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.module }}
          path: |
            ${{ matrix.module }}/build/reports/tests/test/
            ${{ matrix.module }}/build/test-results/test/

      - name: Upload JAR artifact âœˆï¸
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.module }}
          path: |
            ${{ matrix.module }}/build/libs/*-SNAPSHOT.jar
            !${{ matrix.module }}/build/libs/*-plain.jar

  coverage-report:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code â™»ï¸
        uses: actions/checkout@v4

      - name: Set up JDK 25 ğŸ”§
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for gradlew ğŸ›‚
        run: chmod +x gradlew

      - name: Run all tests ğŸ§ª
        run: ./gradlew test

      - name: Generate aggregated coverage report ğŸ”¨
        run: ./gradlew jacocoRootReport

      - name: Upload aggregated coverage report âœ…
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-aggregated
          path: |
            build/reports/jacoco/jacocoRootReport/html/
            build/reports/jacoco/jacocoRootReport/jacocoRootReport.xml
            build/reports/jacoco/jacocoRootReport/jacocoRootReport.csv

      - name: Generate JaCoCo Badge ğŸ“¦
        if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' }}
        uses: cicirello/jacoco-badge-generator@v2
        with:
          jacoco-csv-file: build/reports/jacoco/jacocoRootReport/jacocoRootReport.csv
          badges-directory: build/reports/jacoco/test/html/badges

      - name: Publish coverage report to GitHub Pages ğŸš€
        if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/reports/jacoco/test/html
